// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0xDslET_kJesaea1TnmnnNkbpt94QE7I',
    appId: '1:651605535947:android:1c5af8de74c2d896683f4e',
    messagingSenderId: '651605535947',
    projectId: 'workshop-666c4',
    storageBucket: 'workshop-666c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrHCHEWJIIq5RoiE23OHCkPu5goF1ELqY',
    appId: '1:651605535947:ios:73668b8cfb58cc72683f4e',
    messagingSenderId: '651605535947',
    projectId: 'workshop-666c4',
    storageBucket: 'workshop-666c4.appspot.com',
    androidClientId: '651605535947-09i82m60st2lofg9il3sospfgolm4fbs.apps.googleusercontent.com',
    iosClientId: '651605535947-l6bojvl9hh9h145e3j1oaqojmggvgs8k.apps.googleusercontent.com',
    iosBundleId: 'net.redlinesoft.boilerplate',
  );
}
