// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDU_luucIfoCzwc9cA8S7oiBZWwYr4BU',
    appId: '1:558917745472:android:bd291d5ccbf4b9021198a5',
    messagingSenderId: '558917745472',
    projectId: 'workshop-14e8d',
    storageBucket: 'workshop-14e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf0ZwAGuSg3Fi6529w4lXyk1VMO8KDpYY',
    appId: '1:558917745472:ios:cc859eff0956b99c1198a5',
    messagingSenderId: '558917745472',
    projectId: 'workshop-14e8d',
    storageBucket: 'workshop-14e8d.appspot.com',
    androidClientId: '558917745472-2bke83ete17rb3mdsivdrr75go0ojird.apps.googleusercontent.com',
    iosClientId: '558917745472-h23tn24hndn3rq3uj8en1g3fs384gb6h.apps.googleusercontent.com',
    iosBundleId: 'net.redlinesoft.boilerplate',
  );
}
